# Generated by Django 6.0.5 on 2026-06-04 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_nublado_telegram", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telegramgroupsettings",
            name="language",
            field=models.CharField(
                choices=[("en", "common.language.en"), ("es", "common.language.es")],
                default="en",
                max_length=8,
            ),
        ),
    ]
